//
// Created by Aarjav Jain on 19/07/23.
//

#ifndef RUBIKSCUBESOLVER_GENERICRUBIKSCUBE_H
#define RUBIKSCUBESOLVER_GENERICRUBIKSCUBE_H


class genericRubikscube {

};


#endif //RUBIKSCUBESOLVER_GENERICRUBIKSCUBE_H
